spring:
  application:
    name: vault-demo
  cloud:
    vault:
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        backend: secret
        application-name: vault-demo
