services:
  vault:
    image: hashicorp/vault:1.18.3
    container_name: spring_boot_vault_container
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config:ro  # Mount config directory
    command: [ "vault", "server", "-config=/vault/config/config.hcl" ]
    cap_add:
      - IPC_LOCK
    depends_on:
      mysql:
        condition: service_healthy  # Wait for MySQL to be healthy
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: spring_boot_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: vault_demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql/data

networks:
  app_network:

volumes:
  mysql_data:
  sql_data: